version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    environment:
      - PORT=4000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - TELEGRAM_INIT_SECRET=${TELEGRAM_INIT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app/backend
    depends_on:
      - frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    environment:
      - VITE_PUBLIC_BACKEND_URL=${VITE_PUBLIC_BACKEND_URL:-http://localhost:4000}
      - VITE_TON_CONNECT_MANIFEST_URL=${VITE_TON_CONNECT_MANIFEST_URL:-/tonconnect-manifest.json}
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app/frontend
volumes:
  db-data:
